### ISSUE TITLE
Missing format (or I miss it)

### ISSUE THREAD

**Issue by David-Maran** [selective-php/transformer#5]
There is no more specific rule like alphanum string: string (true, [a-Z0-9])?

**Comment by odan** [comment]
This is intentional, as you can add your own filters if needed.

Example:

```php
$transformer->registerFilter(
    'alphanum',
    function ($value) {
        return preg_replace('/[^\da-z]/i', '', $value);
    }
);
```

**Comment by David-Maran** [comment]
Thank you very much Odan for your explanation.
