### ISSUE TITLE
The documentation about registering filter classes is not up-to-date

### ISSUE THREAD

**Issue by kees-yesco** [selective-php/transformer#7]
According to the documentation you can register filter classes like this (and it should also be possible to create own filter classes and register them like this).
```
// Convert the value using the sprintf function
$transformer->registerFilter('sprintf', SprintfFilter::class);
```

But when you register filter classes like this you get an error:
```
Selective\Transformer\ArrayTransformer::registerFilter(): Argument #2 ($filter) must be of type callable, string given
```

You actually need to register the filter classes like this:
```
$transformer->registerFilter('sprintf', new SprintfFilter());
```

**Comment by odan** [comment]
Update: Yes, the documentation is not correct. Can you please create a PR?

**Comment by kees-yesco** [comment]
Pull request: https://github.com/selective-php/transformer/pull/8

**Comment by odan** [comment]
Thanks for the PR.
